import numpy as np
import matplotlib.pyplot as plt
import random

# Set the seed
np.random.seed(2) #seed function is used to fix the value generated by random module in 2 or any number u pass in parameter

# In place of 2 u can use any number but if u want the data generated while using 2 you have to enter 2 again

x = np.random.randint(1,100,size=50)

# Define bins for 0–20, 20–40, et
intervals = list(range(0,101,20)) #bin parameter sets the intervals be on x axis 

plt.xlabel("Marks Of Student",fontsize=15)
plt.ylabel("Number of Students",fontsize=15)
plt.title("Histogram Chart",fontsize=20)

plt.hist(x , edgecolor = "k", bins=intervals , linewidth = 3 , color="g", alpha=0.5 , orientation = "vertical")
plt.show()


